CREATE TYPE interval_option AS ENUM ('week', 'month');

CREATE TABLE habits (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(72) NOT NULL,
    description TEXT,
    num_times INTEGER NOT NULL,
    time_interval interval_option NOT NULL,
    date_created TIMESTAMPTZ DEFAULT now() NOT NULL
);