
CREATE TYPE habit_units AS ENUM ('daily', 'monthly', 'weekly');

CREATE TABLE habits (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    habit_name varchar(200) NOT NULL,
    description TEXT,
    num_times INTEGER NOT NULL,
    unit_time habit_units NOT NULL, -- do I need ENUM TYPES thing here to select between day, week, month?
    -- dates_completed TEXT[], -- this is an array of dates the habit was completed
    date_created TIMESTAMP DEFAULT now() NOT NULL,
    date_modified TIMESTAMP DEFAULT now()
);

CREATE TABLE habit_records (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    date_completed TIMESTAMP NOT NULL,
    habit_id int REFERENCES habits(id) NOT NULL
);
