CREATE TABLE habits (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    habit_name TEXT NOT NULL,
    description TEXT,
    num_times INTEGER NOT NULL,
    unit_time TEXT NOT NULL, -- do I need ENUM TYPES thing here to select between day, week, month?
    dates_accomplished TEXT[], -- this is an array of dates the habit was accomplished
    date_created TIMESTAMP DEFAULT now() NOT NULL,
    date_modified TIMESTAMP DEFAULT now()
);