CREATE TABLE habit_records (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    date_completed TEXT NOT NULL,
    habit_id int REFERENCES habits(id) NOT NULL
);

-- CREATE TABLE habit_records (
--     id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
--     date_completed TIMESTAMP NOT NULL,
--     habit_id int REFERENCES habits(id) NOT NULL
-- );