CREATE TABLE users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(72) NOT NULL,
    email varchar(72) NOT NULL,
    password varchar(72) NOT NULL,
    date_created TIMESTAMPTZ DEFAULT now() NOT NULL
);

ALTER TABLE habits
  ADD COLUMN
    user_id INTEGER REFERENCES users(id)
    ON DELETE SET NULL;